{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kobo
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  # The kobo sidecar nginx will do further host-based routing...
  rules:
  - host: {{ .Values.kpi.subdomain }}.{{ .Values.general.externalDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-kobo
          servicePort: 80
  - host: {{ .Values.kobocat.subdomain }}.{{ .Values.general.externalDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-kobo
          servicePort: 80
  - host: {{ .Values.enketo.subdomain }}.{{ .Values.general.externalDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-kobo
          servicePort: 80
  tls:
  - hosts:
    - '*.oneacrefund.org'
    secretName: oaf-tls
{{- end -}}
