# The Enketo conf needs to be a Secret because it includes passwords
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  apiKey: {{ .Values.enketo.apiKey | b64enc }}
  encryptionKey: {{ .Values.enketo.encryptionKey | b64enc }}
  djangoSecret: {{ .Values.general.djangoSecret | b64enc }}
  superUserPassword: {{ .Values.general.superUser.password | b64enc }}
  mongoRootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  mongoPassword: {{ .Values.mongodb.auth.password | b64enc }}
  postgresPostgresPassword: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  postgresPassword: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  kobocatDBURL: {{ include "kc_dburl" . | b64enc }}
  kpiDBURL: {{ include "kpi_dburl" . | b64enc }}
  smtpPassword: {{ .Values.smtp.password | b64enc }}
  redisPassword: {{ .Values.global.redis.password | b64enc }}
  redisURLSession: {{ include "redis_url_session" . | b64enc }}
  redisURLLock: {{ include "redis_url_lock" . | b64enc }}
  redisURLBroker: {{ include "redis_url_kobobroker" . | b64enc }}
  redisURLKPIBroker: {{ include "redis_url_kpibroker" . | b64enc }}
