# Load-balancer for SGW
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-kobo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    org.kobotoolbox.instance: {{ .Release.Name }}-kobo
  ports:
  - targetPort: 8000
    port: 8000
    name: kpi
  - targetPort: 8001
    port: 8001
    name: kobocat
  - targetPort: 8005
    port: 8005
    name: enketo
  type: {{ .Values.serviceType }}
