apiVersion: v1
kind: ConfigMap
metadata:
  name: kobo-mongo-init
  namespace: {{ .Release.Namespace }}
data:
  index.js: |
    db.getSiblingDB('{{ .Values.mongodb.auth.database }}').instances.createIndex( { _userform_id: 1 } )
  create-user.js: |
    db.createUser({
      user: "{{ .Values.mongodb.auth.username }}",
      pwd: "{{ .Values.mongodb.auth.password }}",
      roles: [ { role: 'readWrite', db: "{{ .Values.mongodb.auth.database }}" } ]
    })
