# General

kobocat:
  image:
    name: kobotoolbox/kobocat
    tag: '2.020.50'
  subdomain: kc

kpi:
  image:
    name: kobotoolbox/kpi
    tag: '2.020.51'
  subdomain: kobo
  # Background image override (base64 encoded)
  signupPhoto: 

enketo:
  image:
    name: kobotoolbox/enketo-express-extra-widgets
    tag: '2.3.10'
  # Override those!
  apiKey: WEHQJCXHJ2XOBXGOGMXCUJYXQP9ZZFVY4FHLCSKJIWAWPTCMGMECGNBCHXVBFCFT1H5TQTQCKB0J7DF2X23WC7EHOCCVQ7K8CY6QO9C8NMERACUM6S2QQEER
  encryptionKey: w0RkyuQSB33md8cZB5Xx
  lessSecureEncryptionKey: wUNQWPwA3bDVzckKKtS4
  subdomain: ee

general:
  externalDomain: example.com
  externalScheme: http
  externalPort: 
  djangoSecret: EKMvRtT2RFB3xDvFty4SVCsTyaQAHS9aA2mkRqtTp9zQYz48fp
  debug: false
  superUser:
    username: kobo
    password: kobo
  supportEmail: support@example.com
  storageSize: 10Gi
  serviceType: ClusterIP
  # set this to true in order to force internal resolution of external domains. Useful for troubleshooting, but won't work if the schemes are different...
  forceInternal: false

ingress:
  enabled: false
  annotations: {}

external:
  google:
    apiKey: 
    analyticsToken: 
  ravenDSN:
    kobocat: 
    kpi: 
    kpiJs:

smtp:
  host: smtp.gmail.com
  tls: true
  port: '587'
  user: 
  password: 
  from: 

global:
  redis:
    password: brFdS9b7Xp
  storageClass: standard

rediscache:
  enabled: true
  usePassword: true
  cluster:
    # disable slaves
    enabled: false
    slaveCount: 1

redismain:
  enabled: true
  usePassword: true
  cluster:
    # disable slaves
    enabled: false
    slaveCount: 1

mongodb:
  enabled: true
  # TODO: support external db

  # See https://artifacthub.io/packages/helm/bitnami/mongodb for mongodb values doc
  auth:
    rootPassword: kobo
    username: kobo
    password: kobo
    database: formhub
  initdbScriptsConfigMap: kobo-mongo-init

postgresql:
  enabled: true
  kobocatDatabase: kobocat
  kpiDatabase: koboform

  # TODO: support external db

  # Standard postgres chart values
  # See https://artifacthub.io/packages/helm/bitnami/postgresql for docs
  postgresqlPostgresPassword: admin
  postgresqlUsername: kobo
  postgresqlPassword: kobo
  initdbScriptsConfigMap: kobo-postgres-init
