# kobocat is the standard OpenRosa form server that form filling apps will connect to
kobocat:
  image:
    # We're using an immutable tag here to avoid surprises
    # see https://hub.docker.com/r/kobotoolbox/kobocat for latest tags
    name: kobotoolbox/kobocat
    tag: '2.020.50'
  subdomain: kc

# kpi is the main Kobotoolbox UI
kpi:
  image:
    # See https://hub.docker.com/r/kobotoolbox/kpi
    name: kobotoolbox/kpi
    tag: '2.020.51'
  subdomain: kobo
  # Background image override (base64 encoded)
  signupPhoto: 

# Enketo is the web-based form preview and filling UI
enketo:
  image:
    # See https://hub.docker.com/r/kobotoolbox/enketo-express-extra-widgets
    name: kobotoolbox/enketo-express-extra-widgets
    tag: '2.3.10'
  subdomain: ee
  # Override those!
  apiKey: WEHQJCXHJ2XOBXGOGMXCUJYXQP9ZZFVY4FHLCSKJIWAWPTCMGMECGNBCHXVBFCFT1H5TQTQCKB0J7DF2X23WC7EHOCCVQ7K8CY6QO9C8NMERACUM6S2QQEER
  encryptionKey: w0RkyuQSB33md8cZB5Xx
  lessSecureEncryptionKey: wUNQWPwA3bDVzckKKtS4

general:
  # The subdomains MUST be reachable since the application will try to call itself at this address
  # If you don't have a working domain yet, you may use forceInternal below to resolve it to the pod's localhost IP
  externalDomain: example.com
  externalScheme: http
  externalPort: 
  djangoSecret: EKMvRtT2RFB3xDvFty4SVCsTyaQAHS9aA2mkRqtTp9zQYz48fp
  debug: false
  # This user will have access to kobotoolbox UI but also the built-in Django admin interface (/admin)
  superUser:
    username: kobo
    password: kobo
  supportEmail: support@example.com
  storageSize: 10Gi
  serviceType: ClusterIP
  # set this to true in order to force internal resolution of external domains.
  # Useful for troubleshooting, but won't work if the schemes are different...
  forceInternal: false

ingress:
  enabled: false
  annotations: {}

external:
  google:
    apiKey: 
    analyticsToken: 
  ravenDSN:
    kobocat: 
    kpi: 
    kpiJs:

smtp:
  host: smtp.gmail.com
  tls: true
  port: '587'
  user: 
  password: 
  from: 

global:
  redis:
    # Override this!
    password: brFdS9b7Xp
  # Will be used by this and all subcharts
  storageClass: standard

rediscache:
  enabled: true
  usePassword: true
  cluster:
    # disable slaves
    enabled: false
    slaveCount: 1

redismain:
  enabled: true
  usePassword: true
  cluster:
    # disable slaves
    enabled: false
    slaveCount: 1

mongodb:
  enabled: true
  # TODO: support external db
  # For now we only support a db installed with a subchart

  # See https://artifacthub.io/packages/helm/bitnami/mongodb for mongodb values doc
  auth:
    rootPassword: kobo
    username: kobo
    password: kobo
    database: formhub
  initdbScriptsConfigMap: '{{ .Release.Name }}-mongo-init'

postgresql:
  enabled: true
  kobocatDatabase: kobocat
  kpiDatabase: koboform

  # TODO: support external db
  # For now we only support a db installed with a subchart

  # Standard postgres chart values
  # See https://artifacthub.io/packages/helm/bitnami/postgresql for docs
  postgresqlPostgresPassword: admin
  postgresqlUsername: kobo
  postgresqlPassword: kobo
  initdbScriptsConfigMap: '{{ .Release.Name }}-postgres-init'
